### ISSUE TITLE
Add to Homebrew

### ISSUE THREAD

**Issue by KevinVecchione** [particledecay/kconf#50]
Adding `kconf` to Homebrew would be a nice quality-of-life improvement:
https://docs.brew.sh/Adding-Software-to-Homebrew

**Comment by particledecay** [comment]
Ok so it definitely took me a while to get this going, but it's finally in!
![image](https://github.com/particledecay/kconf/assets/685255/07587402-ee4d-422c-baa4-d88eb538a7f7)
