### ISSUE TITLE
kconf fetch - feature idea

### ISSUE THREAD

**Issue by kingdonb** [particledecay/kconf#51]
First I wanted to say, great job creating `kconf`! I found your post on Reddit one day, and I said I'd likely be back with issues

This tool has definitely made it into my daily use toolbag and solves well above 80% of my problems handling kubeconfig files. 🎉 

I thought maybe `kconf` could add a feature that takes a Kubernetes API server URL and fetches the CA from that URL, one time, then stores it in a named cluster for you in your existing kubeconfig?

A new problem has popped up, and before I build another standalone tool to solve it for me, it has occurred to me that it might have a most elegant solution in `kconf`. Let's briefly talk about my configuration so there is some context for this feature, since otherwise it might not be obvious why I need it:

#### kubelogin support with Dex issuer

I have set up my Kubernetes API server for OIDC authentication with Dex. So I created my own Issuer (dex) and I'm using GitHub Groups to provide the claims. I have a `kubelogin` configuration that uses, from my kubeconfig, a single `user` that gets an OIDC token, and with a single admin group I'm able to drive access to many clusters. I am using this with vclusters right now, they get provisioned via a CAPI provider for vcluster 🎉 this is working great, except I am still copying kubeconfigs around.

So each new vcluster gets a configuration adjustment:
* [make cluster OIDC enabled](https://github.com/kingdonb/bootstrap-repo/blob/a0c8424c645481ab9ab1d7f31caaef6fdb3a18ae/clusters/howard-moomboo-space/clusters/test/limnocentral.yaml#L47-L50)

and with this adjustment, I no longer need to copy kubeconfig around – almost!

#### still needs certificate authority data

I can dispense with the client certificate key and client certificate data, but since my Kubernetes cluster does not come from a central certificate authority (sidenote, maybe I can fix that, but I think it is conventional to be self-signed here) each cluster has a self-signed cert of its own, and the kubeconfig needs to have at least `clusters.cluster.certificate-authority-data`.

In the end this will still be a bit clunky to recommend for users of my "managed service" – telling them to fetch the certificate and just trust DNS this one time, probably not the experience I want to provide, so I'll probably maintain an ACL somehow with a list of the clusters that they should have access to, and provide a "download kubeconfig" button for them to click that gets the latest CA data of all clusters ahead of time and bundles them all together, so they can simply throw their old kubeconfig away and get a new one if ever a `certificate-authority-data` is new or needs to be replaced.

But in the mean time, I'd love to have a good way I can recommend to users for managing their own cert authority data without resorting to opening an editor and putting some base64 data in by hand. Is this a feature you think maybe belongs in kconf at all?

**Comment by kingdonb** [comment]
Well, I wrote a nice little go function that [fetches the CA data from a kube API server](https://github.com/kingdonb/github-app-secret/blob/9b445222c4232dc3b732ae6a60dadd81f9388614/cmd/kubeconfig-ca-fetch/main.go#L86-L105) in case you're so inclined to adapt this into a feature for `kconf`!

Thanks for the inspiration to get some Go chops of my own, welcome to close this if not interested in the feature 🎉

**Comment by kingdonb** [comment]
Thanks! I kept iterating, and found that my first approach was unreliable.

But the second approach I tried, was successful and I'm using it now every day:
https://github.com/kingdon-ci/kubeconfig-ca-fetch/blob/main/kubeconfig.go

I wrote some comments that may help if you're trying to implement it now. I didn't really know what I was doing, like I said first Go code in a while.

**Comment by particledecay** [comment]
Hey it's been a while. Sorry for the late follow-up. I thought I wrote a response but just realized I didn't. I feel like this change may be a bit removed from kconf's core purpose to just work with kubeconfigs. The only thing it's fetching remotely at all is namespace information for autocompletion. If you think I'm wrong feel free to reopen, but I'm closing this for now. I appreciate you opening this discussion!

**Comment by kingdonb** [comment]
I agree. I solved it for myself with a stand-alone tool, and it's likely I'll continue to develop that tool. I still use kconf 👍
