### ISSUE TITLE
Plan to add two commands to change context and namespace 

### ISSUE THREAD

**Issue by bzd111** [particledecay/kconf#7]
plan to add two commands to change context and namespace
# How to use
## change context
If k8s has this context, will print change sucess,  else print change faild
`kconf ctx context-name` 

## change namespace
If k8s's context has this namespace, will print change sucess, else print change faild
`kconf ns ns-name`

**Comment by particledecay** [comment]
If you're going to do this, I would prefer to limit the amount of new commands. In both cases you're changing the default setup of your current context, so I would suggest keeping them under one command.

Something like `kconf use myContext myNamespace`. I'd much prefer the `use` command.

**Comment by particledecay** [comment]
@bzd111 funny, after you posted this, I have been in situations where I really wanted this command.

**Comment by bzd111** [comment]
I am doing a part of  change context name. I will commit partial feature as soon as.

**Comment by particledecay** [comment]
Awesome, `kconf use` works great. I also went ahead and added `kconf u` (and short aliases for the other commands as well, like `kconf ls`).
